server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/order-api/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/inventory-api/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: shipping-service
          uri: ${SHIPPING_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/shipping-api/**
          filters:
            - StripPrefix=1
            - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: logistics-gateway
            client-secret: secret
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_FRONTEND_URL:http://localhost:8090/realms/logistics-realm}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_BACKEND_URL:http://localhost:8090/realms/logistics-realm}/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_BACKEND_URL:http://localhost:8090/realms/logistics-realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_BACKEND_URL:http://localhost:8090/realms/logistics-realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
