server:
  port: 8080
  forward-headers-strategy: framework

grpc:
  client:
    inventory-service:
      address: 'static://localhost:9091'
      negotiationType: PLAINTEXT
    shipping-service:
      address: 'static://localhost:9092'
      negotiationType: PLAINTEXT

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/logistics_db?createDatabaseIfNotExist=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
  cloud:
    stream:
      bindings:
        order-out-0:
          destination: order-events
      rabbit:
        bindings:
          order-out-0:
            producer:
              routing-key-expression: '''orderCreated'''
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/logistics-realm}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/logistics-realm}/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

services:
  inventory:
    url: http://localhost:8081/inventory
  shipping:
    url: http://localhost:8082/shipping

springdoc:
  swagger-ui:
    path: /swagger
